### PR TITLE
TS extensions, and a merge of riak_ts-develop

### PR DESCRIPTION
**Pull request by hmmr**
Required by https://github.com/basho/riak_test/pull/1185.

Proposing to merge riak_ts-develop, with a new module `rhc_ts` to handle TS API requests. These are used in riak_test/ts_simple_http_security_SUITE.

### CODE REVIEW

**Comment by bsparrow435** [comment]
👍

**Comment by bsparrow435** [comment]
👍 R15 support is still needed

**Comment by javajolt** [comment]
@bsparrow435 What needs to be added for R15?

**Comment by bsparrow435** [comment]
@javajolt already fixed by the most recent commits from @hmmr. We're still supporting R15 for the clients at this time. No supported versions of RIak use it anymore but on the client side users could be running whatever.

**Pull request merged**
